# Numpy Basics by Mrittika Megaraj

# Numpy

In [1]:
l1=[1,2,3,4,5]

In [2]:
l1+5

TypeError: can only concatenate list (not "int") to list

In [3]:
l1/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [4]:
import numpy as np

In [5]:
ar1=np.array([1,2,3,4,5])

In [6]:
type(ar1)

numpy.ndarray

In [7]:
ar1

array([1, 2, 3, 4, 5])

In [8]:
# 2D array
ar_2D=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [9]:
ar_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
l1

[1, 2, 3, 4, 5]

In [11]:
ar2=np.array(l1)

In [12]:
type(ar2)

numpy.ndarray

In [13]:
t1=(1,2,3,4,5)

In [14]:
type(t1)

tuple

In [15]:
ar3=np.array(t1)

In [16]:
type(ar3)

numpy.ndarray

In [17]:
ar3

array([1, 2, 3, 4, 5])

In [18]:
print(dir(ar1))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [19]:
ar4=np.arange(0,21,2)
ar4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
ar5=np.linspace(1,20,10,dtype=int)
ar5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20])

In [21]:
np.random.random(20)

array([0.41750976, 0.88753088, 0.75400892, 0.67281514, 0.83596342,
       0.3219251 , 0.52425191, 0.08843268, 0.07214202, 0.35478599,
       0.01432808, 0.12397409, 0.14478798, 0.81881406, 0.21691611,
       0.68076671, 0.09984738, 0.59979366, 0.34438947, 0.85416865])

In [22]:
np.random.randint(1,20,10)

array([ 4,  3,  2,  5,  9,  3, 13,  8, 19, 15])

In [23]:
ar1

array([1, 2, 3, 4, 5])

In [24]:
ar5=np.arange(1,21)

In [25]:
ar5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
ar5_2D=np.reshape(ar5,(5,4))

In [27]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [28]:
ar5_3D=np.reshape(ar5,(2,5,2))

In [29]:
ar5_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [30]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [31]:
np.transpose(ar5_2D)

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [32]:
np.arange()

TypeError: arange() requires stop to be specified.

In [33]:
ar5.

SyntaxError: invalid syntax (2171679232.py, line 1)

## Inspection of arrays

In [34]:
ar5_2D.shape

(5, 4)

In [35]:
ar5_2D.size

20

In [36]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [37]:
ar5_2D.ndim

2

In [38]:
ar1

array([1, 2, 3, 4, 5])

In [39]:
ar1.ndim

1

In [40]:
ar5_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [41]:
ar5_3D.ndim

3

In [42]:
ar5_3D.dtype

dtype('int32')

In [43]:
ar5_3D.nbytes

80

## Accessing elements 

In [44]:
ar1

array([1, 2, 3, 4, 5])

In [45]:
ar1[0]

1

In [46]:
ar1[1]

2

In [47]:
ar1[-1]

5

In [48]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [49]:
ar5_2D[2,2]

11

In [50]:
ar5_2D[4,3]

20

In [51]:
ar5_2D[2,1]

10

In [52]:
ar1

array([1, 2, 3, 4, 5])

In [53]:
ar1[1:4]

array([2, 3, 4])

In [54]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [55]:
ar5_2D[1,1:3]

array([6, 7])

In [56]:
ar1

array([1, 2, 3, 4, 5])

In [57]:
ar1[:]

array([1, 2, 3, 4, 5])

In [58]:
ar5_2D[:,1]

array([ 2,  6, 10, 14, 18])

In [59]:
ar1

array([1, 2, 3, 4, 5])

In [60]:
ar1[::3]

array([1, 4])

In [61]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [62]:
ar5_2D[:,0::3]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16],
       [17, 20]])

In [63]:
ar5_2D[:,3]

array([ 4,  8, 12, 16, 20])

In [64]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [65]:
# Last row 
ar5_2D[4::,::]

array([[17, 18, 19, 20]])

In [66]:
# 10,11,14,15
ar5_2D[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [67]:
#10,11,12,13,14,15
ar5_2D[2:4,1:4]

array([[10, 11, 12],
       [14, 15, 16]])

## Update

In [68]:
ar1

array([1, 2, 3, 4, 5])

In [69]:
ar1[1]=21

In [70]:
ar1

array([ 1, 21,  3,  4,  5])

## Mathematical operations

In [71]:
ar1

array([ 1, 21,  3,  4,  5])

In [72]:
ar1+5

array([ 6, 26,  8,  9, 10])

In [73]:
ar1-5

array([-4, 16, -2, -1,  0])

In [74]:
ar1*3

array([ 3, 63,  9, 12, 15])

In [75]:
ar1

array([ 1, 21,  3,  4,  5])

In [76]:
ar2

array([1, 2, 3, 4, 5])

In [77]:
ar1+ar2

array([ 2, 23,  6,  8, 10])

In [78]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [79]:
ar5_2D*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [80]:
ar1

array([ 1, 21,  3,  4,  5])

In [81]:
ar5_2D+ar1

ValueError: operands could not be broadcast together with shapes (5,4) (5,) 

In [82]:
ar7=[1,2,3,4]

In [83]:
ar5_2D+ar7

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16],
       [14, 16, 18, 20],
       [18, 20, 22, 24]])

In [84]:
ar1.sum()

34

In [85]:
ar1

array([ 1, 21,  3,  4,  5])

In [86]:
ar1.mean()

6.8

In [87]:
ar1.min()

1

In [88]:
ar1.max()

21

In [89]:
ar5_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [90]:
ar5_2D.sum()

210

In [91]:
ar5_2D[:,-1].sum()

60

In [92]:
ar5_2D[0,:].mean()

2.5

In [93]:
ar5_2D[ar5_2D>=10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [94]:
ar5_2D[(ar5_2D>=10) & (ar5_2D<=15)]

array([10, 11, 12, 13, 14, 15])

In [95]:
ar5_2D[ar5_2D%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## Merging arrays

In [96]:
ar1

array([ 1, 21,  3,  4,  5])

In [97]:
ar2

array([1, 2, 3, 4, 5])

In [98]:
np.concatenate((ar1,ar2))

array([ 1, 21,  3,  4,  5,  1,  2,  3,  4,  5])

In [99]:
np.concatenate((ar1,ar2))

array([ 1, 21,  3,  4,  5,  1,  2,  3,  4,  5])

In [100]:
np.vstack((ar1,ar2))

array([[ 1, 21,  3,  4,  5],
       [ 1,  2,  3,  4,  5]])

In [101]:
np.hstack((ar1,ar2))

array([ 1, 21,  3,  4,  5,  1,  2,  3,  4,  5])

In [102]:
np.full((3,3,),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [103]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [104]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [105]:
ar10=np.empty((4,4))

In [106]:
ar10.fill(20)

In [107]:
ar10

array([[20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.]])

In [108]:
ar1

array([ 1, 21,  3,  4,  5])

In [109]:
# Reversing an array
ar1[::-1]

array([ 5,  4,  3, 21,  1])

In [110]:
np.flip(ar1)

array([ 5,  4,  3, 21,  1])

In [111]:
# copy method and view method
ar10=np.copy(ar1)

In [112]:
ar11=ar1.view()

In [113]:
ar1

array([ 1, 21,  3,  4,  5])

In [114]:
ar10

array([ 1, 21,  3,  4,  5])

In [115]:
ar11

array([ 1, 21,  3,  4,  5])

In [116]:
ar1[1]=15

In [117]:
ar1

array([ 1, 15,  3,  4,  5])

In [118]:
ar10

array([ 1, 21,  3,  4,  5])

In [119]:
ar11

array([ 1, 15,  3,  4,  5])

In [120]:
# Given list of weights in kilograms
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]
# Import Numpy
import numpy as np
# Create a numpy array np_weight_kg from weight_kg
np_weight_kg = np.array(weight_kg)
# Create np_weight_lbs from np_weight_kg by converting from kilograms to pounds
np_weight_lbs = np_weight_kg * 2.2
# Print out np_weight_lbs
print(np_weight_lbs)

[179.63  214.544 209.55  204.556 189.596 194.59 ]


In [121]:
#method 1
import numpy as np
# Original array
original_array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20])
# Reverse array using slicing with step -1
reverse_array = original_array[::-1]
# Print the original and reversed arrays
print("Original array:")
print(original_array)
print("Reverse array:")
print(reverse_array)


Original array:
[12 13 14 15 16 17 18 19 20]
Reverse array:
[20 19 18 17 16 15 14 13 12]


In [122]:
#method 2
import numpy as np
# Original array
original_array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20])
# Reverse array using np.flip()
reverse_array = np.flip(original_array)
# Print the original and reversed arrays
print("Original array:")
print(original_array)
print("Reverse array:")
print(reverse_array)

Original array:
[12 13 14 15 16 17 18 19 20]
Reverse array:
[20 19 18 17 16 15 14 13 12]
